### ISSUE TITLE
"unable to initialize a scanner"

### ISSUE THREAD

**Issue by abelsromero** [Azure/container-scan#119]
We have been seeing this error more and more lately and we wonder if this is related to the action or is github infra. Any suggestion would be greatly apreciated.

```
 Scanning for vulnerabilties in image: ***/***/----:------
Error: FATAL	scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
Error: An error occurred while scanning container image: ***/***/-----:------ for vulnerabilitie
```

**Comment by koushdey** [comment]
@abelsromero Can you share the screenshot of the log or share the run log url? Are you still facing this issue? Have you recently onboarded to container-scan action?

**Comment by abelsromero** [comment]
> @abelsromero Can you share the screenshot of the log or share the run log url? Are you still facing this issue? Have you recently onboarded to container-scan action?

That's the only log that is shown. But whatever it was it hasn't happened lately.

**Comment by koushdey** [comment]
May be an intermittent issue with the docker scanner. Closing the issue as it has not appeared lately.
