### ISSUE TITLE
Error when scanning image - Trivy - No help topic for image name

### ISSUE THREAD

**Issue by scottwestover** [Azure/container-scan#122]
I am seeing the following error logs when trying to scan an image:

```
/usr/bin/tar --version
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/027f57e6-0bba-4a99-87b7-823b887b56bb -f /home/runner/work/maven-consumer-profile/maven-consumer-profile/_temp/tools/trivy
##[debug]Caching tool trivy 0.23.0 x64
##[debug]source dir: /home/runner/work/_temp/027f57e6-0bba-4a99-87b7-823b887b56bb
##[debug]destination /opt/hostedtoolcache/trivy/0.23.0/x64
##[debug]finished caching tool
##[debug]Trivy executable found at path  /opt/hostedtoolcache/trivy/0.23.0/x64/trivy
Scanning for vulnerabilties in image: test_docker_for_scan
ommand]/opt/hostedtoolcache/trivy/0.23.0/x64/trivy test_docker_for_scan
##[debug]No help topic for 'test_docker_for_scan'
##[debug]
Error: An error occurred while scanning container image: test_docker_for_scan for vulnerabilities.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Scan Docker Image
```

I think this issue might be tied to the latest release of trivy: `0.23.0`. In this release, there were breaking changes: https://github.com/aquasecurity/trivy/discussions/1652, where the `trivy` command is no longer supported and you must use `trivy image`.

Here is an example snippet of my current GitHub Workflow file:

```yaml
- name: Build Docker image and Push to GitHub Packages
  uses: docker/build-push-action@v2
  with:
    context: .
    load: true
    push: false
    pull: true
    tags: |
      test_docker_for_scan
- name: Scan Docker Image
  uses: azure/container-scan@v0
  with:
    image-name: test_docker_for_scan
    username: USER
    password: ${{ secrets.GITHUB_TOKEN }}
```

This issue just started happening today. If you need any additional details, please let me know.

**Comment by rohank07** [comment]
Also getting the same error

**Comment by Viktork25** [comment]
Getting the same issue when I am trying to scan the image. I have open the debug in my Github Action and you can see below the issue that I get:

`##[debug]Downloading https://api.github.com/repos/aquasecurity/trivy/releases/latest
##[debug]Downloading /home/runner/work/_temp/5f8ee519-b302-46e3-b940-934302f53f1c
##[debug]download complete
##[debug]isExplicit: 0.23.0
##[debug]explicit? true
##[debug]checking cache: /opt/hostedtoolcache/trivy/0.23.0/x64
##[debug]not found
##[debug]Could not find trivy in cache, downloading from https://github.com/aquasecurity/trivy/releases/download/v0.23.0/trivy_0.23.0_Linux-64bit.tar.gz
##[debug]Downloading https://github.com/aquasecurity/trivy/releases/download/v0.23.0/trivy_0.23.0_Linux-64bit.tar.gz
##[debug]Downloading /home/runner/work/test/test/_temp/tools/trivy
##[debug]download complete
/usr/bin/tar --version
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/49f60ca7-6581-4643-b881-1f6b843af353 -f /home/runner/work/test/test/_temp/tools/trivy
##[debug]Caching tool trivy 0.23.0 x64
##[debug]source dir: /home/runner/work/_temp/49f60ca7-6581-4643-b881-1f6b843af353
##[debug]destination /opt/hostedtoolcache/trivy/0.23.0/x64
##[debug]finished caching tool
##[debug]Trivy executable found at path  /opt/hostedtoolcache/trivy/0.23.0/x64/trivy
Scanning for vulnerabilties in image: test-image
ommand]/opt/hostedtoolcache/trivy/0.23.0/x64/trivy test-image9a
##[debug]No help topic for 'test-image'
##[debug]
Error: An error occurred while scanning container image: test-image for vulnerabilities.
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Azure Container image scan`

I think that 4 hours ago a new version of trivy has been released, the 0.23 which started causing the issues that we get above

**Comment by patrick-stephens** [comment]
Same here, if it is a Trivy version issue it would be good to be able to pin that version in future.

**Comment by lloydnye** [comment]
I think pinning the version, or at least making it configurable as an input is the right thing to do. 

The underlying issue looks to be a breaking change from trivy which changes the command from `trivy` to `trivy image`
https://github.com/aquasecurity/trivy/discussions/1515

I think it could be a simple change here https://github.com/Azure/container-scan/blob/580b077b44ccdff6a6d28e4ab82231cfd96ebd45/src/trivyHelper.ts#L16

**Comment by koushdey** [comment]
Updated the binaries in `v0` and `v0.1`. Please verify.

**Comment by scottwestover** [comment]
@koushdey Thank you for reviewing and releasing the updates. Both `v0` and `v0.1` are working for me.
