### ISSUE TITLE
Latest update needs a labeled release

### ISSUE THREAD

**Issue by larryclaman** [Azure/container-scan#131]
The PR #29  was fix for a breaking change; however the repo owners neglected to create a versioned [release ](https://github.com/Azure/container-scan/releases) for this code, meaning that anyone using it will need to refer to it by commit hash (yuck).  eg `uses: azure/container-scan@b5317f7365a8e3aab8e35d97e932d105ad2ed4e8`

Repo owners, please create a labeled release for this latest update.

**Comment by koushdey** [comment]
I am not sure why are you using the commit hash. The commit you shared is for latest commit on master branch. The same changes are already upto date on [release branch](https://github.com/Azure/container-scan/commits/releases/v0) and releases (pls refer screenshot below).
![Screenshot 2022-02-07 at 1 51 35 PM](https://user-images.githubusercontent.com/57134947/152750738-cdc067bc-b5f9-4d41-8e28-4a1f9a4d05db.png)

The PR you mentioned is again for master. The corresponding PR for release is #27. Please use the releases directly in your workflows. Let me know if you are still facing the issue.

**Comment by larryclaman** [comment]
Hi @koushdey, as I mentioned in the other issue, the fact that the releases were 'bumped' to reflect the latest code is what confused me, plus the fact that the date did not get updated on the release page (See screenshot)

In other words, if I understand correctly, the two pinned releases v0 and v0.1 contain the latest fix for the breaking change in trivy.  Yet the dates showing for these releases did not change.  Personally, I find this confusing.


![Screenshot 2022-02-07 075749](https://user-images.githubusercontent.com/25161683/152793203-c6e9325d-6563-48ac-9bed-0186f73c9694.png)

**Comment by koushdey** [comment]
@larryclaman This is something that has to be raised with the Github Marketplace team. The date is from the time when the release was created
