### ISSUE TITLE
Error: Error while parsing allowedlist file. Error: TypeError: Cannot read property 'general' of undefined

### ISSUE THREAD

**Issue by shyam-ks** [Azure/container-scan#137]
Run Azure/container-scan@v0
  with:
    image-name: ghcr.io/xxxxxxxx/fxxxxxx:1.0.46-64eae5a
    username: xxxx
    password: ***
    severity-threshold: HIGH
    token: ***
    run-quality-checks: true
  env:
    GHCR_REPO: ghcr.io/bentlynevada-bh
Error: Error while parsing allowedlist file. Error: TypeError: Cannot read property 'general' of undefined

**Comment by koushdey** [comment]
Have you installed scanitizer app in your repo?

**Comment by shyam-ks** [comment]
> Have you installed scanitizer app in your repo?

Yeah. that was the issue. Removed it, Thanks
