### ISSUE TITLE
Not available on Github actions store

### ISSUE THREAD

**Issue by ddotpdot** [Azure/container-scan#21]
This seems to be quite a helpful action for the community.

It seems like the azure/container-scan@v1 is not available on the github actions marketplace.
Is it not published yet? https://github.com/marketplace?type=actions

**Comment by ds-ms** [comment]
@ddotpdot We'll be publishing it soon!

**Comment by ddotpdot** [comment]
@ds-ms  great! will check it out. thanks

**Comment by bb-deepak** [comment]
@ds-ms 
works great. 
where can i share some suggestions and improvements and possibly PR's?

**Comment by ddotpdot** [comment]
@ds-ms
works great.
where can i share some suggestions and improvements and possibly PR's?

**Comment by ds-ms** [comment]
You can post your suggestions & improvements on this repo. 😃 
Create an issue for feature request or some bugs you found.

**Comment by jonpulsifer** [comment]
Soon is ten days ago and people are looking at this now, can we get this out the door? 😄 🚀

**Comment by ds-ms** [comment]
@jonpulsifer I did a `Pre-Release` of this action: https://github.com/marketplace/actions/container-image-scan 

We had some moving pieces so didn't release it till now. But I don't see any harm in doing a pre-release. 

You're free to use it now; but there are still are some, potentially breaking, changes to come! You'll want to upgrade to that eventually. Will keep you posted on this. 

Keeping this thread open until we're done with the remaining changes.

**Comment by jonpulsifer** [comment]
Thanks! We are playing with `azure/container-scan@releases/v0` for now as you mentioned and will keep an eye out

**Comment by jonpulsifer** [comment]
Thanks again friends, the pre-release is working great for us.

**Comment by ds-ms** [comment]
This action has been released in the marketplace.
