### ISSUE TITLE
Provide flag to not fail action if thresholds are met

### ISSUE THREAD

**Issue by tylerauerbeck** [Azure/container-scan#26]
I'm currently trying to add this action to my workflow and would like to be able to proceed with additional steps of my job after this scan is run. Currently the action fails after this scan because of high vulnerabilities, which in turn doesn't allow these steps to run. Is this already possible? Or would this be something that could added?

**Comment by shigupt202** [comment]
@tylerauerbeck You can use `continue-on-error: true` along with the action in your workflow.
Please refer to this for more information about continue-on-error: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error
