### ISSUE TITLE
Multiple occurrences of same vulnerabilities in Trivy's output

### ISSUE THREAD

**Issue by shigupt202** [Azure/container-scan#28]
We can see multiple occurrences of same CVE's in the output. This is because same vulnerability can be present in multiple packages used in the image. Also, it's not very intuitive to identify the source (package) of the vulnerability from the output. 
We can add another field to indicate the package in which each CVE is found to resolve both these issues. 

![image](https://user-images.githubusercontent.com/57620559/83144484-09411e80-a111-11ea-9d55-d23f0bb89f94.png)

Ref: https://github.com/Azure/container-scan/issues/25

**Comment by shigupt202** [comment]
cc: @ammohant @azooinmyluggage

**Comment by ds-ms** [comment]
Is there a way to differentiate if you directly use the tool though?

**Comment by shigupt202** [comment]
Yes, Trivy's output contains a `Target` field which can be used to identify the source of vulnerabilities.

**Comment by ds-ms** [comment]
Is it sparse or does it have data for every entry? If it isn't sparse, then `target` seems like an expected column addition. 
We probably shouldn't truncate that data!

**Comment by shigupt202** [comment]
It's slightly different from the other fields. The detected vulnerabilities are grouped on the basis of package in which they were detected. So each target is associated with a bunch of vulnerabilities. 
![image](https://user-images.githubusercontent.com/57620559/83221750-41d60c00-a194-11ea-8ff6-7daee047fb1a.png)

**Comment by ajinkya599** [comment]
We should append `target` to each row. That's useful information!

**Comment by ds-ms** [comment]
I agree with @ajinkya599

**Comment by ds-ms** [comment]
@ammohant @ajinkya599 should we go ahead with this enhancement then?

**Comment by ds-ms** [comment]
Paging @ammohant @ajinkya599 @shigupt202

**Comment by shigupt202** [comment]
Adding @anraghun

**Comment by anraghun** [comment]
Yes, this looks good to me. If trivy is providing `target`, then we should surface it.

**Comment by ammohant** [comment]
Is there an ask where we need to list unique vulnerabilities across packages ?

**Comment by shigupt202** [comment]
@ammohant Not knowing the source of the package can cause some confusion. For instance, one user reported this [issue](https://github.com/Azure/container-scan/issues/25).

**Comment by ammohant** [comment]
No Iam not saying that  target is not the identifier.  I am saying that in ADDITION should be interpret this and have a view which presents unique vulnerabilities -> list of package/target.   The question I had was has there been such an ask which will help many.  Of course, it can be inferred given the curr output but is a different view is need from people ?

**Comment by shigupt202** [comment]
So far, we have not received any such requests from the users (apart from the aforementioned issue). But we can consider updating the check run view in case people face any such confusion.
