### ISSUE TITLE
Vague error message : `Looks like the scanitizer app is not installed on the repo`

### ISSUE THREAD

**Issue by grzesuav** [Azure/container-scan#35]
```
Creating scan result. image_name: metacontrollerio/metacontroller:lint, head_sha: aad6c67946130f3cc49b3c5db312f504dc6a2ddb
Looks like the scanitizer app is not installed on the repo. Falling back to check run creation through GitHub actions app...
```

what is `scanitizer` app ?  There is no mention of it in README, also I tried to search on Github Marketplace but no luck

**Comment by ds-ms** [comment]
This is Work In Progress @grzesuav that's one of the reasons why this action is still in `Pre-Release` 

cc: @ajinkya599 / @shigupt202

**Comment by shigupt202** [comment]
You can now install [Scanitizer](https://github.com/apps/scanitizer) app on your repo (though it's still in beta). Let us know if you have any suggestions or feedbacks. 😃
