### ISSUE TITLE
Fails on Local image?

### ISSUE THREAD

**Issue by blairdrummond** [Azure/container-scan#49]
Our scans seem to be failing when used on an image within the github action

https://github.com/StatCan/kubeflow-containers/runs/1467927330#step:6:24

The error no-longer occurs if we scan an image that has already been pushed to the acr. (But, of course, we'd prefer to scan *before* pushing)

Is this expected behaviour? Do you have any recommendations for how to address this?

**Comment by shigupt202** [comment]
@blairdrummond This seems to be an issue with the underlying tool, Trivy that the action is using. Here are a few possible solutions that I could find:
1. Try scanning the local image without giving it a label
2. Set an environment variable `TRIVY_TIMEOUT_SEC=360s` on the GitHub runner.

**Comment by blairdrummond** [comment]
Thanks! Sorry, it makes sense that this is an issue with the upstream tool not this action. I will move the issue.
