### ISSUE TITLE
Suggestion: expose ignore-unfixed option of trivy

### ISSUE THREAD

**Issue by mateus-amarante** [Azure/container-scan#61]
I suggest adding an option to set the --ignore-unfixed flag of [trivy](https://github.com/aquasecurity/trivy). Personally, I'm more interested in this selected group, and it makes me opt for [trivy-action](https://github.com/aquasecurity/trivy-action) to check vulnerabilities in my repositories.

**Comment by mateus-amarante** [comment]
Actually, I've just noticed there exists the environment variable TRIVY_IGNORE_UNFIXED. I think it works very well for me. Then, I'm closing the issue.

**Comment by mo-at-dave** [comment]
@mateus-amarante - how did you pass that in your CI?
