### ISSUE TITLE
Add comments on vulnerable places

### ISSUE THREAD

**Issue by grzesuav** [Azure/container-scan#65]
Would be useful if scan would finish with comments added in PR in problematic places

**Comment by shigupt202** [comment]
@grzesuav We do have an app ([Scanitizer](https://github.com/apps/scanitizer)) which comments on the PR's and also creates a commit to add an allowedlist file for the vulnerabilities. However, the capabilities of the app are limited to allowedlist file currently.

**Comment by grzesuav** [comment]
thanks, will check it out
