### ISSUE TITLE
Got warning message in CI pipeline

### ISSUE THREAD

**Issue by akphi** [Azure/container-scan#71]
Hi,

I see this warning in my pipeline and I don't really know where it comes from:
https://github.com/finos/legend-shared/runs/2104257137?check_suite_focus=true

```
An error occurred while creating the check run for container scan. Error: Error: An error occurred while creating scan result. Statuscode: 403, StatusMessage: Forbidden, head_sha: efc00c4ff11ee8caacfa882e743f8eefb4261af7
```

**Comment by ds-ms** [comment]
@akphi is this happening consistently?

**Comment by ds-ms** [comment]
Have you tried installing this app: https://github.com/apps/scanitizer on your repo? 
Perhaps it's failing because of that. While posting the check-run, the action interacts with this app. You can find the link for the same above this section: https://github.com/Azure/container-scan#example-yaml-snippets 

@shigupt202 didn't we have a more verbose warning before?

**Comment by shigupt202** [comment]
@ajinkya599 might have more context on this.

**Comment by ds-ms** [comment]
@ajinkya599 / @shigupt202 we should also consider fixing the README to highlight the app installation instructions maybe? Cause it's public now

**Comment by akphi** [comment]
@ds-ms in the README, it says that this is totally optional and I feel that it should be so, especially when we don't have a lot of docs on what the app is about (we clearly don't have any doc about the app there), and generally, I would prefer to not install too many applications to my repo unless it's absolutely necessary.

I understand it's just a warning so it's not blocking, but I think it would be nice to maybe have an option to surpress this. I think a lot of folks are like me who only cares about using this for the `trivy` and `Dockle` run on their github actions

**Comment by ds-ms** [comment]
>Now IMHO, I really think if what we should do is if the app is not installed, we don't say anything about it in the CI build, even warning, because warning like this creates ambiguity and people might think they need to install the app. What do you think?

We were banking on the GitHub Action's token for creating a check run if the app wasn't installed. Based on the permissions listed here: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token it should have been able to do it, unless if yours is a forked repo. 
@shigupt202 perhaps we should make this error a little more verbose to point out that it was the ${{ github.token }} which lacked permissions to create a check-run

**Comment by akphi** [comment]
> We were banking on the GitHub Action's token for creating a check run if the app wasn't installed. Based on the permissions listed here: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token it should have been able to do it, unless if yours is a forked repo.

Hm, that's a fair point, but here I thought the idea is to tell people to install `Scanitizer`, but like I explained, not every user would like to install the application, given that the job of the application is to post comments to PR, so yes, we can be verbose if the application is not installed, but if the users intentionally choose not to install the app, there should be a way to suppress that warning.

So there are usually 2 ways: be `completely silent` about it or be very `noisy` about it, but give a flag to suppress that warning. If we let this run in fork with a lot of warning and no suppress flag, that gives an incentive for people to consider not to run this plugin in PR CI just to workaround that, which is quite sad because `container-scan` is blazing fast, totally worthwhile to run in PR pipeline, and it would be great to know if my container is secure per PR changes.

Perhaps I said too much here 😭 but I felt like this is such a great tool and I just felt obliged to make it closer to perfect. But if you don't want to implement a way to suppress the warning, please let me know, I will happily close this issue.

**Comment by shigupt202** [comment]
@akphi Just want to clarify that this error that you're seeing in the logs is not because you've not installed `Scanitizer`. We just print this message (not a warning or error) in the logs in case the app is not present, and create a check run locally from the action. The users are free to use the action without getting any warnings/errors even if they don't install `Scanitizer`.
```
Looks like the scanitizer app is not installed on the repo. Falling back to check run creation through GitHub actions app...
For a better experience with managing allowedlist, install Scanitizer app from https://github.com/apps/scanitizer.
```
You're seeing this error because when the action creates a check run locally (for a better summary view), it's not able to do so because your token doesn't have enough permissions (because of the limitation that @ds-ms pointed about forked repos).

**Comment by akphi** [comment]
Got it. So when we're in the CI running on `master`, I should see no warning whatsoever then. Then yes, it makes sense to make it more comprehensible like what @ds-ms was saying, though please don't leverage it too much to become a [`github-actions` warning](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message), a normal warning print in the log is totally cool with me.

Do you guys want me to leave this open, or should I close it?
