### ISSUE TITLE
Settings when action should return error

### ISSUE THREAD

**Issue by Smuu** [Azure/container-scan#84]
Currently the action only return an error code, when the trivy scan return an error.

It would be helpful to set the severity/level for the vulnerabilities/best-practices when the action should return an error.

**Comment by ajinkya599** [comment]
Hi @Smuu, it is not clear what is the desired outcome here. Can you please share an example to help us understand the use case better.

**Comment by ajinkya599** [comment]
Closing this issue. Please feel free to re-open with more details.
