### ISSUE TITLE
Option to exclude base image?

### ISSUE THREAD

**Issue by csmcallister** [Azure/container-scan#98]
Is there an option to exclude the base image for a scan akin to the`--exclude-base` option available in the `docker scan` cli? Here's the [relevant docker scan doc section](https://docs.docker.com/engine/scan/#supported-options).

**Comment by ajinkya599** [comment]
This action uses Trivy for scanning the container images. At this point Trivy doesn't seem to support this.
You may want to open a request upstream.

**Comment by csmcallister** [comment]
Thank you for the clarification @ajinkya599 

There's already an upstream issue for this in case others are interested: aquasecurity/trivy/issues/1198
