### ISSUE TITLE
Available for commercial use?

### ISSUE THREAD

**Issue by timmeinerzhagen** [Azure/container-scan#99]
Trivy uses vulnerability database sources, that are only licensed for non-commercial use. They state this at the bottom of [the Trivy overview page](https://aquasecurity.github.io/trivy/v0.17.0/) and there is an issue open on this aquasecurity/trivy#491.

As this action uses Trivy, I would assume it is also not available for use within commercial applications, right?

**Comment by ajinkya599** [comment]
@pulkitaggarwl Can you please look into this query?

**Comment by pulkitaggarwl** [comment]
@azooinmyluggage / @Nagi-MSFT  can you share some guidance here ?

**Comment by azooinmyluggage** [comment]
I think we should abide by the terms that Aqua has defined.
1. Add a disclaimer in this Actions readme right away. @ajinkya599 and @pulkitaggarwl can you do it right away?
2. Work with MSFT legal team on guidance. I will loop in ASC team to figure out the right long term solution.

**Comment by koushdey** [comment]
Hey @azooinmyluggage, any chance you got in touch with the legal and ASC team?

**Comment by azooinmyluggage** [comment]
@koushdey Please add a disclaimer in this Actions readme right away.
I am escalating with ASC team.

**Comment by koushdey** [comment]
@azooinmyluggage I think the disclaimer is already added by @ajinkya599 as part of #101

**Comment by azooinmyluggage** [comment]
Thanks. I have reached out to my previous point of contact i ASC team as there has been no response from Raj

**Comment by azooinmyluggage** [comment]
Update from ASC team

> There is a conversation with CELA that I started for this. I can’t readily share it since it is ACP. I can state that there is no legal risk to Microsoft at the moment. Please give us a few weeks to update the customer messaging, and reconcile this with other offerings being developed for CI/CD.

**Comment by itaysk** [comment]
Hello, this is Itay Shakury from Aqua Security. as you can see in linked issue (https://github.com/aquasecurity/trivy/issues/491), the reason for this notice is just the SafetyDB vulnerability feed, but I'm happy to share that Trivy no longer depends on it. This is already merged and the next release of Trivy will remove this commercial restriction notice. In general, Trivy (as all of our OSS) is licensed under Apache 2 and we want as many people/companies as possible using it freely.

**Comment by azooinmyluggage** [comment]
Thanks @itaysk That is great to know.

**Comment by koushdey** [comment]
I think we are good to close this issue based on comments from @itaysk.
